added workflow to get orig issue on pr comment

diff --git a/.github/workflows/backport-command.yml b/.github/workflows/backport-command.yml
--- a/.github/workflows/backport-command.yml
+++ b/.github/workflows/backport-command.yml
@@ -27,34 +27,17 @@ jobs:
           CLIENT_PAYLOAD: ${{ toJson(github.event.client_payload) }}
         id: type
         run: |
+          branches=$(gh api "/repos/${TARGET_ORG}/${TARGET_REPO}/branches" --jq '.[] | select(.name=='\"$ARG1\"')')
+          if [[ $branches == "" ]]; then
+            echo "Branch name not found"
+            exit 1
+          fi
           if [[ $(echo $CLIENT_PAYLOAD | jq 'has("pull_request")') == true ]]; then
             commented_on=pr
           else
             commented_on=issue
           fi
           echo "::set-output name=commented_on::$commented_on"
-          branches=$(gh api "/repos/${TARGET_ORG}/${TARGET_REPO}/branches" --jq '.[] | select(.name=='\"$ARG1\"')')
-          if [[ $branches == "" ]]; then
-            # not a branch; checking if its a PR
-            pulls=$(gh api "repos/${TARGET_ORG}/${TARGET_REPO}/pulls/$ARG1" --jq '. | select(.state=="closed")')
-            if [[ $pulls == "" ]]; then
-              echo "The provided argument is neither branch nor a pr"
-              exit 2
-            else
-              # case valid PR number
-              if [[ "$commented_on" == "pr" ]]; then
-                echo "Provided PR number in PR comment. You should use PR numbers only on issue somments"
-                exit 2
-              else
-                echo "::set-output name=type::pr"
-              fi
-            fi
-          else
-            # case valid branch name
-            # this case applies for both creating issue and PRs
-            # thus it is accepted in any case
-            echo "::set-output name=type::branch"
-          fi
 
   # creates backport issue if commented on issue, or
   # creates backport PR if commented on PR
@@ -159,7 +142,7 @@ jobs:
           ORIG_TITLE: ${{ github.event.client_payload.github.payload.issue.title }}
           BACKPORT_COMMITS: ${{ steps.backport_commits.outputs.backport_commits }}
           IS_MERGED: ${{ github.event.client_payload.pull_request.merged }}
-        id: head_branch
+        id: pr_details
         run: |
           if [[ "$IS_MERGED" != true ]]; then
             msg="The pull request is not merged yet. Cancelling..."
@@ -169,6 +152,11 @@ jobs:
               --repo "$TARGET_ORG/$TARGET_REPO"
             exit 1
           fi
+          fixing_issue_url=$(gh pr view "$PR_NUMBER" --repo "$TARGET_ORG/$TARGET_REPO" --json body --jq .body \
+            | grep 'close\|fix\|resolve' \
+            | grep ' https://github.com/\|:https://github.com/\|: https://github.com' \
+            | grep -Eo '(http.*)' | head -1 \
+            || "")
           # ensure unique branch
           suffix=$(echo $(($RANDOM % 1000)))
           # git config --global user.email "vbot@vectorized.io"
@@ -185,6 +173,7 @@ jobs:
           git push --set-upstream origin $head_branch
           git remote rm upstream
           echo ::set-output name=head_branch::$head_branch
+          echo ::set-output name=fixing_issue_url::$fixing_issue_url
 
       - name: Create pull request
         if: needs.backport-type.outputs.commented_on == 'pr'
@@ -195,31 +184,43 @@ jobs:
           ORIG_TITLE: ${{ github.event.client_payload.github.payload.issue.title }}
           ORIG_REVIEWERS: ${{ steps.reviewers.outputs.reviewers }}
           ORIG_ISSUE_URL: ${{ github.event.client_payload.github.payload.issue.html_url }}
-          HEAD_BRANCH: ${{ steps.head_branch.outputs.head_branch }}
+          HEAD_BRANCH: ${{ steps.pr_details.outputs.head_branch }}
+          FIXING_ISSUE_URL: ${{ steps.pr_details.outputs.fixing_issue_url }}
+          ORIG_PR_NUMBER: ${{ github.event.client_payload.pull_request.number }}
         run: |
-          # close
-          # closes
-          # closed
-          # fix
-          # fixes
-          # fixed
-          # resolve
-          # resolves
-          # resolved
-          
-          issue_number=$(gh issue list --repo "${TARGET_ORG}/${TARGET_REPO}" \
-            --state open \
-            --search "[${BACKPORT_BRANCH}] ${ORIG_TITLE} in:title" \
-            --json number \
-            --milestone "${TARGET_MILESTONE}" \
-            --jq '.[0].number')
-          if [[ "$issue_number" == "" ]]; then
-            issue_number="Not Found. Please add manually"
-          fi
           label_exists=$(gh label list --repo "$TARGET_ORG/$TARGET_REPO" --limit 500 | grep "kind/backport")
           if [[ "$label_exists" == "" ]]; then
             gh label create "kind/backport" --repo "$TARGET_ORG/$TARGET_REPO"
           fi
+          if [[ "$FIXING_ISSUE_URL" != "" ]]; then
+            orig_issue_number=$(echo "$FIXING_ISSUE_URL" | awk -F/ '{print $NF}')
+            orig_issue_title=$(gh issue view "$orig_issue_number" --json title --jq .title)
+
+            backport_issue_url=$(gh issue list --repo "${TARGET_ORG}/${TARGET_REPO}" \
+            --state open \
+            --search "[${BACKPORT_BRANCH}] ${orig_issue_title} in:title" \
+            --json url \
+            --milestone "${TARGET_MILESTONE}" \
+            --jq '.[0].url')
+
+            if [[ "$backport_issue_url" == "" ]]; then
+              # backport issue does not exist and will be created
+              # get orig issue assignees
+              orig_issue_assingees=$(gh issue view "$orig_issue_number" --json assignees --jq .assignees.[].login | paste -s -d ',' -)
+              # create issue
+              backport_issue_url=$(gh issue create --title "[${BACKPORT_BRANCH}] ${orig_issue_title}" \
+                --label "kind/backport" \
+                --repo "${TARGET_ORG}/${TARGET_REPO}" \
+                --assignee "${orig_issue_assingees}" \
+                --milestone "${TARGET_MILESTONE}" \
+                --body "Backport ${FIXING_ISSUE_URL} to branch ${BACKPORT_BRANCH}")
+              # post a comment on original PR
+              gh pr comment "$ORIG_PR_NUMBER" \
+                --body "Created backport issue $backport_issue_url" \
+                --repo "$TARGET_ORG/$TARGET_REPO"
+            fi
+          fi
+          
           gh pr create --title "[${BACKPORT_BRANCH}] ${ORIG_TITLE}" \
             --base "${BACKPORT_BRANCH}" \
             --label "kind/backport" \
@@ -229,7 +230,7 @@ jobs:
             --reviewer "${ORIG_REVIEWERS}" \
             --milestone "${TARGET_MILESTONE}" \
             --body """Backport from pull request: ${ORIG_ISSUE_URL}
-            Fixes $issue_number
+            Fixes $backport_issue_url
             """
 
       - name: Add reaction
